
version: '3'

services:
  app: 
    
    container_name: app
    
    entrypoint: 
      - /bin/sh
      - -c
      - |
        chmod +x ./start.sh && \
        wait-for db:3306 -t 40 -- ./start.sh
    
    tty: true
    build: 
      context: ./app  
     
    volumes:
      - ./app:/usr/src/app
    ports:
      - "3000:3000"
    networks:
      - nodenetwork
    depends_on:
      - db
  nginx:
    container_name: nginx
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://app:3000"]
      interval: 5s
      timeout: 10s
      retries: 3
    build: 
      context: ./nginx
    networks:
      - nodenetwork
    ports:
      - "8080:80"

    depends_on:
      - app
    
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodenetwork
networks:
  nodenetwork:
    driver: bridge